apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-booking-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hotel-booking
  template:
    metadata:
      labels:
        app: hotel-booking
    spec:
      containers:
      - name: hotel-booking-app
        image: arpitbaiju/hotel-booking-system:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always