apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hotel-system
  template:
    metadata:
      labels:
        app: hotel-system
    spec:
      containers:
      - name: hotel-container
        image: hotel-booking-system:latest
        ports:
        - containerPort: 8080